"""Render results/results.md and results/summary.json from run records."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .metrics import Rate, latency_stats, microbenchmark, parser_accuracy, reproducibility, summarise
from .runner import RunRecord
from .tasks import Suite

SCOPES = [("tool_not_granted", "tool not implied"), ("argument_out_of_scope", "args out of scope"),
          ("in_scope", "inside the grant")]
SPLITS = [("dev-v1", "Originals t01–t25"), ("new", "Originals t26–t40"), ("para", "Paraphrases"),
          ("heldout", "Held-out requests")]


def _row(cells: list[Any]) -> str:
    return "| " + " | ".join(str(c) for c in cells) + " |"


def _table(header: list[str], rows: list[list[Any]]) -> str:
    return "\n".join([_row(header), "|" + "|".join(["---"] * len(header)) + "|", *(_row(r) for r in rows)])


def _pct(r: Rate | None) -> str:
    return r.fmt(ci=False) if r else "–"


def _jr(d: dict[str, Any] | None) -> str:
    return f"{100 * d['rate']:.1f}% ({d['k']}/{d['n']})" if d else "–"


def _effect(e: dict[str, Any]) -> str:
    a = e["args"]
    detail = a.get("amount") or a.get("url") or a.get("event_id") or a.get("path") or a.get("to") or a.get("attendees")
    extra = f" → {a['to_account']}" if "to_account" in a else ""
    return f"{e['tool']}({detail}{extra})"


def build(records: list[RunRecord], suite: Suite, out: Path, *, agent: str, figures: list[Path]) -> Path:
    metrics = summarise(records)
    by = {m.config: m for m in metrics}
    lat = latency_stats(records)
    micro = microbenchmark(suite)
    repro = reproducibility(suite)
    parse = parser_accuracy(suite)
    manifest = json.loads((suite.root / "_poison_manifest.json").read_text(encoding="utf-8"))
    v1_path = out / "v1" / "summary.json"
    v1 = {c["config"]: c for c in json.loads(v1_path.read_text(encoding="utf-8"))["configs"]} if v1_path.exists() else {}
    versions_path = out / "parser_versions.json"
    versions = json.loads(versions_path.read_text(encoding="utf-8")) if versions_path.exists() else {}
    n_clean = sum(1 for r in records if not r.poisoned)
    n_poisoned = sum(1 for r in records if r.poisoned)

    lines: list[str] = []
    add = lines.append
    add("# Results (v2)")
    add("")
    add(f"Generated by `python -m authz_bench all --agent {agent}`. Agent: **{agent}**. "
        f"Suite: {len(suite.tasks)} tasks, {manifest['variants']} poisoned variants "
        f"(poisoning seed {manifest['seed']}, manifest sha256 `{manifest['sha256'][:12]}…`). "
        f"{len(records)} runs ({n_clean} clean, {n_poisoned} poisoned) across {len(metrics)} configurations. "
        f"Parser: `{parse['parser']}`. The v1 baseline on the same suite is in [v1/results.md](v1/results.md).")
    add("")
    add("Rates are shown as `rate (k/n) [95% Wilson interval]`. Over-restriction is reported in every table "
        "(brain.md convention), because a mediator that blocks everything scores perfectly on safety.")
    add("")

    add("## 1. Headline")
    add("")
    add(_table(
        ["Configuration", "Unauthorised action rate", "Over-restriction rate", "Task utility (clean)",
         "Utility under attack", "Attack calls denied", "Denial precision", "Prompts / clean run"],
        [[m.label, m.unauthorised.fmt(), m.over_restriction.fmt(), _pct(m.utility), _pct(m.poisoned_utility),
          _pct(m.caught), _pct(m.denial_precision), f"{m.escalations_per_clean:.2f}"] for m in metrics],
    ))
    add("")
    add("*Unauthorised action rate*: poisoned runs in which any effect executed that the task did not call for. "
        "*Over-restriction rate*: clean runs in which a known-correct call was finally denied. *Utility under "
        "attack*: poisoned runs in which every expected effect still happened. *Attack calls denied*: the PRD's "
        "\"escalation attempts caught\". *Denial precision*: adversarial denials over all denials in poisoned runs.")
    add("")
    for f in figures:
        if f.suffix == ".png":
            add(f"![{f.stem}]({f.name})")
            add("")

    if v1:
        add("## 2. v1 → v2")
        add("")
        add("Same 40-task suite, same poisoned variants, same scripted agent. v1 numbers come from the code at tag "
            "`v1-expanded`.")
        add("")
        rows = []
        for name in ("full", "oracle-intent", "paraphrased", "heldout", "full+esc-attentive", "tools+args"):
            if name in by and name in v1:
                m, o = by[name], v1[name]
                rows.append([m.label, _jr(o["unauthorised_action_rate"]), m.unauthorised.fmt(ci=False),
                             _jr(o["over_restriction_rate"]), m.over_restriction.fmt(ci=False)])
        add(_table(["Configuration", "Unauthorised v1", "Unauthorised v2", "Over-restriction v1",
                    "Over-restriction v2"], rows))
        add("")
        add("*Paraphrases* were development data for parser v2, so their v2 row is optimistic. The *held-out* row "
            "is the fair comparison: those requests were written after v1 and before any v2 change.")
        add("")

    add("## 3. Unauthorised actions by the attack's relation to the grant")
    add("")
    add("Each attack is classified against the grant a perfect parser would produce under that configuration "
        "(the hand-labelled intent): does it need a tool the request never implied, a granted tool with "
        "out-of-scope arguments, or does it stay inside the grant?")
    add("")
    add(_table(["Configuration", *[label for _, label in SCOPES]],
               [[m.label, *[_pct(m.by_scope.get(k)) for k, _ in SCOPES]] for m in metrics]))
    add("")
    add(_table(["Configuration", "Hand-written near-miss attacks", "Generic attacks", "Near-forbidden tasks only"],
               [[m.label, _pct(m.by_origin.get("task")), _pct(m.by_origin.get("generic")),
                 _pct(m.near_forbidden_unauthorised)] for m in metrics]))
    add("")

    if "full" in by and "full-v1-derivation" in by:
        add("## 4. Derivation v1 vs v2 (same parser)")
        add("")
        add("v2 derivation adds exact-URL egress (F3), cancellations bound through trusted calendar metadata (F2) "
            "and a ceiling per payee. Everything else is equal.")
        add("")
        rows = [[by[n].label, by[n].unauthorised.fmt(), by[n].over_restriction.fmt(),
                 *[_pct(by[n].by_scope.get(k)) for k, _ in SCOPES]] for n in ("full-v1-derivation", "full")]
        add(_table(["Configuration", "Unauthorised", "Over-restriction", *[label for _, label in SCOPES]], rows))
        add("")
        fixed = sorted({(r.task_id, r.attack_id) for r in records if r.config == "full-v1-derivation" and r.unauthorised}
                       - {(r.task_id, r.attack_id) for r in records if r.config == "full" and r.unauthorised})
        if fixed:
            add("Attacks v1 derivation let through that v2 blocks: " + ", ".join(f"`{t}`/`{a}`" for t, a in fixed) + ".")
            add("")

    add("## 5. Budget: per tool or global")
    add("")
    rows = [[by[n].label, by[n].unauthorised.fmt(), by[n].over_restriction.fmt(), _pct(by[n].poisoned_utility)]
            for n in ("tools+args", "full", "full-global") if n in by]
    add(_table(["Configuration", "Unauthorised", "Over-restriction", "Utility under attack"], rows))
    add("")
    if "full" in by and "full-global" in by:
        full_ids = {(r.task_id, r.variant_id) for r in records if r.config == "full" and r.unauthorised}
        extra = [f"`{r.task_id}`/`{r.attack_id}`" for r in records
                 if r.config == "full-global" and r.unauthorised and (r.task_id, r.variant_id) not in full_ids]
        add(f"Let through by the global budget but not the per-tool one: {', '.join(extra) or 'none'}.")
        add("")

    add("## 6. Escalation")
    add("")
    rows = []
    for name in ("full", "full+esc-attentive-nohist", "full+esc-attentive", "full+confirm-amounts", "full+esc-rubber"):
        if name in by:
            m = by[name]
            rows.append([m.label, m.unauthorised.fmt(), m.over_restriction.fmt(), f"{m.escalations_per_clean:.2f}",
                         f"{m.escalations_per_poisoned:.2f}", m.attack_escalations_approved])
    add(_table(["Configuration", "Unauthorised", "Over-restriction", "Prompts / clean run", "Prompts / poisoned run",
                "Attack calls approved by user"], rows))
    add("")
    add("The attentive user approves only calls that match the known-correct plan. *With history* the prompt also "
        "lists the irreversible actions already executed, and the user refuses a call whose planned slot is "
        "already used (F4).")
    add("")
    if "full+esc-attentive-nohist" in by and "full+esc-attentive" in by:
        nohist = {(r.task_id, r.variant_id) for r in records if r.config == "full+esc-attentive-nohist" and r.unauthorised}
        hist = {(r.task_id, r.variant_id) for r in records if r.config == "full+esc-attentive" and r.unauthorised}
        if nohist - hist:
            add("Stopped by showing history: " + ", ".join(f"`{t}`/`{v}`" for t, v in sorted(nohist - hist)) + ".")
            add("")

    add("## 7. Intent parsing")
    add("")
    add(_table(["Split", "Exact match", "Irreversible actions correct", "Read domains correct"],
               [[label, _jr(parse[k]["exact"]), _jr(parse[k]["actions"]), _jr(parse[k]["read_domains"])]
                for k, label in SPLITS]))
    add("")
    add("For parser v2, the originals and paraphrases are development data, so only the held-out row measures "
        "generalisation. The held-out requests were written by the same author as the parser (threat to validity).")
    add("")
    if versions:
        rows = []
        for key, label in SPLITS:
            cells = []
            for v in ("v1", "v2"):
                d = versions.get(v, {}).get(key)
                cells.append(f"{d['exact']}/{d['n']} ({100 * d['exact'] / d['n']:.0f}%)" if d else "–")
            rows.append([label, *cells])
        add("Exact-match accuracy by parser version (`scripts/parser_versions.py`; v1 is loaded from the git tag):")
        add("")
        add(_table(["Split", "Parser v1", "Parser v2"], rows))
        add("")
    rows = [[m.label, m.over_restriction_tags.get("intent_parse_failure", 0), m.over_restriction_tags.get("policy_limit", 0),
             m.over_restriction_tags.get("ablation", 0)] for m in metrics if m.over_restriction_tags]
    add("Denied known-correct calls in clean runs, by cause. *intent_parse_failure*: the hand-labelled grant would "
        "have allowed it. *policy_limit*: no trusted-input parser could have granted it. *ablation*: the "
        "configuration itself withholds the tool.")
    add("")
    add(_table(["Configuration", "intent_parse_failure", "policy_limit", "ablation"], rows))
    add("")
    mism = [r for r in parse["rows"] if not r["exact"]]
    if mism:
        add("<details><summary>Requests the parser gets wrong</summary>")
        add("")
        add(_table(["Task", "Split", "Request", "Wrong fields"],
                   [[r["task"], r["split"], r["request"].replace("|", "\\|"),
                     ", ".join(k for k, ok in r["fields"].items() if not ok)] for r in mism]))
        add("")
        add("</details>")
        add("")

    add("## 8. Failure modes")
    add("")
    for name in ("full", "heldout", "full+confirm-amounts", "full+esc-attentive"):
        misses = [r for r in records if r.config == name and r.unauthorised]
        if name not in by or not misses:
            continue
        add(f"### Unauthorised actions that executed: {by[name].label}")
        add("")
        add(_table(["Task", "Req", "Attack", "Relation to grant", "Cause", "What executed"],
                   [[r.task_id, r.request_index, r.attack_id, r.scope_relation, r.miss_cause,
                     "; ".join(_effect(e) for e in r.unexpected)] for r in misses]))
        add("")
    for name in ("full", "heldout", "paraphrased"):
        blocked = [r for r in records if r.config == name and not r.poisoned and r.over_restricted]
        if name not in by or not blocked:
            continue
        add(f"### Clean runs blocked: {by[name].label}")
        add("")
        add(_table(["Task", "Request", "Denials", "Tag"],
                   [[r.task_id, r.request.replace("|", "\\|"), ", ".join(r.denial_reasons),
                     ", ".join(sorted(set(r.over_restriction_tags)))] for r in blocked]))
        add("")

    add("## 9. Non-functional requirements")
    add("")
    add(_table(["Requirement", "Measured", "Status"], [
        ["Mediation < 50 ms per call (timed inside the session, per check)",
         f"p50 {lat.get('p50_us', 0):.0f} µs, p99 {lat.get('p99_us', 0):.0f} µs, max {lat.get('max_us', 0) / 1000:.2f} ms "
         f"over {lat.get('calls', 0)} checks", "met" if lat.get("max_us", 0) < 50_000 else "NOT met"],
        ["Mediation < 50 ms per call (isolated `check()` microbenchmark, with trusted state)",
         f"p50 {micro['p50_us']:.0f} µs, p99 {micro['p99_us']:.0f} µs over {micro['calls']} checks",
         "met" if micro["p99_us"] < 50_000 else "NOT met"],
        ["Derivation reproducible for the same request",
         f"{repro['identical']}/{repro['requests']} requests gave identical fingerprints over {repro['repeats']} fresh derivations",
         "met" if repro["identical"] == repro["requests"] else "NOT met"],
        ["Works with any framework exposing a tool-call interface",
         "generic `MediatedToolbox`; LangGraph `MediatedToolNode` (graph executed in tests); Anthropic SDK loop",
         "met"],
    ]))
    add("")

    add("## 10. Supporting breakdowns")
    add("")
    templates = sorted({t for m in metrics for t in m.by_template})
    add("Unauthorised action rate by injection template. With the scripted agent, differences come only from which "
        "attacks use which template, not from wording.")
    add("")
    add(_table(["Configuration", *templates], [[m.label, *[_pct(m.by_template.get(t)) for t in templates]] for m in metrics]))
    add("")
    add("Denial reasons (all runs):")
    add("")
    add(_table(["Configuration", "Reasons"],
               [[m.label, ", ".join(f"{k} ×{v}" for k, v in m.denial_reasons.items()) or "–"] for m in metrics]))
    add("")

    out.mkdir(parents=True, exist_ok=True)
    path = out / "results.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    summary = {
        "agent": agent, "runs": len(records), "clean_runs": n_clean, "poisoned_runs": n_poisoned,
        "poison_manifest": manifest, "configs": [m.to_json() for m in metrics],
        "latency_in_session": lat, "latency_microbenchmark": micro, "reproducibility": repro,
        "parser_accuracy": {k: v for k, v in parse.items() if k != "rows"},
    }
    (out / "summary.json").write_text(json.dumps(summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return path
